name: web-url
version: 0.0.1
synopsis: Url
maintainer: eyeinsky <eyeinsky9@gmail.com>
license: MIT
github: eyeinsky/web-url
category: Web

dependencies:
  - base < 5
  - lens
  - text
  - attoparsec

library:
  exposed-modules:
    - URL
    - URL.Core

default-extensions:
  - Arrows
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFunctor
  - DeriveGeneric
  - EmptyDataDecls
  - ExtendedDefaultRules
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - PolyKinds
  - QuasiQuotes
  - RecursiveDo
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - TypeInType
  - TypeOperators
  - TypeSynonymInstances
